snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: redis://redis_docker
        doctrine:
            type: phpredis
            alias: doctrine
            dsn: redis://redis_docker
    doctrine:
        result_cache:
            client: doctrine
            entity_manager: default

# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md for instructions on
# how to configure the bundle.
#
#        default:
#            type: phpredis
#            alias: default
#            dsn: "%env(REDIS_URL)%"
